In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt 
import seaborn as sns

In [2]:
df1=pd.read_csv('country_wise_latest.csv')
df1.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [3]:
df1.isna().sum()

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64

In [4]:
df1=df1.drop(['Confirmed', 'Deaths', 'Recovered', 'Active',
       'New cases', 'New deaths', 'New recovered', 'Deaths / 100 Cases',
       'Recovered / 100 Cases', 'Deaths / 100 Recovered',
       'Confirmed last week', '1 week change', '1 week % increase'],axis=1)

In [5]:
df1.shape

(187, 2)

In [6]:
df2=pd.read_csv('covid_19_clean_complete.csv')
df2.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,22-01-2020,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,22-01-2020,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,22-01-2020,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,22-01-2020,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,22-01-2020,0,0,0,0,Africa

In [7]:
df2['Country/Region'].value_counts()

Country/Region
China             6204
Canada            2256
France            2068
United Kingdom    2068
Australia         1504
                  ...
Holy See           188
Honduras           188
Hungary            188
Iceland            188
Lesotho            188
Name: count, Length: 187, dtype: int64

In [8]:
df2.shape

(49068, 10)

In [9]:
df2=df2.drop(['Province/State','Date','Confirmed','Deaths','Recovered','Active','WHO Region'],axis=1)

In [10]:
df3=pd.read_csv('day_wise.csv')
df3.head()

,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,No. of countries
0,2020-01-22,555,17,28,510,0,0,0,3.06,5.05,60.71,6
1,2020-01-23,654,18,30,606,99,1,2,2.75,4.59,60.00,8
2,2020-01-24,941,26,36,879,287,8,6,2.76,3.83,72.22,9
3,2020-01-25,1434,42,39,1353,493,16,3,2.93,2.72,107.69,11
4,2020-01-26,2118,56,52,2010,684,14,13,2.64,2.46,107.69,13

In [11]:
df4=pd.read_csv('full_grouped.csv')
df4.head()

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean
1,2020-01-22,Albania,0,0,0,0,0,0,0,Europe
2,2020-01-22,Algeria,0,0,0,0,0,0,0,Africa
3,2020-01-22,Andorra,0,0,0,0,0,0,0,Europe
4,2020-01-22,Angola,0,0,0,0,0,0,0,Africa

In [12]:
df5=pd.read_csv('usa_county_wise.csv')
df5.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Date,Confirmed,Deaths
0,16,AS,ASM,16,60.0,NaN,American Samoa,US,-14.271000,-170.132000,"American Samoa, US",1/22/20,0,0
1,316,GU,GUM,316,66.0,NaN,Guam,US,13.444300,144.793700,"Guam, US",1/22/20,0,0
2,580,MP,MNP,580,69.0,NaN,Northern Mariana Islands,US,15.097900,145.673900,"Northern Mariana Islands, US",1/22/20,0,0
3,63072001,PR,PRI,630,72001.0,Adjuntas,Puerto Rico,US,18.180117,-66.754367,"Adjuntas, Puerto Rico, US",1/22/20,0,0
4,63072003,PR,PRI,630,72003.0,Aguada,Puerto Rico,US,18.360255,-67.175131,"Aguada, Puerto Rico, US",1/22/20,0,0

In [13]:
df6=pd.read_csv('worldometer_data.csv')
df6.head()

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa

In [14]:
df6.shape

(209, 16)

In [15]:
df6=df6.drop(['WHO Region'],axis=1)

In [16]:
df6=pd.merge(df6,df1,on='Country/Region')

In [17]:
df6['Population'].dtype

dtype('float64')

In [18]:
df6=df6.drop(['Country/Region','NewCases','NewDeaths','TotalRecovered','NewRecovered','ActiveCases','Deaths/1M pop'],axis=1)

In [19]:
df6.columns

Index(['Continent', 'Population', 'TotalCases', 'TotalDeaths',
       'Serious,Critical', 'Tot Cases/1M pop', 'TotalTests', 'Tests/1M pop',
       'WHO Region'],
      dtype='object')

In [20]:
df6.isna().sum()

Continent            0
Population           0
TotalCases           0
TotalDeaths         12
Serious,Critical    63
Tot Cases/1M pop     0
TotalTests          14
Tests/1M pop        14
WHO Region           0
dtype: int64

In [21]:
df6['Serious,Critical']=df6['Serious,Critical'].fillna(0)

In [22]:
df6=df6.dropna()

In [23]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 0 to 162
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Continent         147 non-null    object
 1   Population        147 non-null    float64
 2   TotalCases        147 non-null    int64
 3   TotalDeaths       147 non-null    float64
 4   Serious,Critical  147 non-null    float64
 5   Tot Cases/1M pop  147 non-null    float64
 6   TotalTests        147 non-null    float64
 7   Tests/1M pop      147 non-null    float64
 8   WHO Region        147 non-null    object
dtypes: float64(6), int64(1), object(2)
memory usage: 11.5+ KB

In [24]:
df6['WHO Region'].unique()

array(['Americas', 'South-East Asia', 'Europe', 'Africa',
       'Eastern Mediterranean', 'Western Pacific'], dtype=object)

In [25]:
df6['Continent'].unique()

array(['South America', 'Asia', 'Europe', 'Africa', 'North America',
       'Australia/Oceania'], dtype=object)

In [26]:
df6['WHO Region']=df6['WHO Region'].map({'Americas':0, 'South-East Asia':1, 'Europe':2, 'Africa':3,
                                         'Eastern Mediterranean':4, 'Western Pacific':5})
df6['Continent']=df6['Continent'].map({'South America':0, 'Asia':1, 'Europe':2, 'Africa':3,
                                        'North America':4, 'Australia/Oceania':5})

In [27]:
cols_to_scale=df6.columns

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df6[cols_to_scale]=scaler.fit_transform(df6[cols_to_scale])

In [28]:
df6.describe()

,Continent,Population,TotalCases,TotalDeaths,"Serious,Critical",Tot Cases/1M pop,TotalTests,Tests/1M pop,WHO Region
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,0.436735,0.026593,0.031766,0.034499,0.035488,0.089815,0.040861,0.072210,0.446259
std,0.243288,0.087419,0.106117,0.110007,0.128399,0.135303,0.114631,0.133700,0.285799
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.200000,0.002033,0.000712,0.000340,0.000000,0.010109,0.002041,0.008369,0.400000
50%,0.400000,0.007322,0.003663,0.001967,0.000783,0.036529,0.008698,0.031904,0.400000
75%,0.600000,0.023048,0.019678,0.014537,0.008330,0.118279,0.032470,0.079532,0.600000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
X=df6.drop('TotalDeaths',axis=1)
y=df6['TotalDeaths']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=45)

In [30]:
from sklearn.linear_model import LinearRegression
model_lr=LinearRegression()
model_lr.fit(X_train,y_train)
model_lr.score(X_test,y_test)

0.8293859786496073